name: dartium_issue
dependencies:
  logging: any
  intl: any
  serialization: any
  test: any
  coverage: any
  polymer: ^1.0.0-rc.15
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  js: ^0.6.0
  analyzer: 0.27.2
  polymer_interop: ^1.0.0-rc.8
  route_hierarchical: any
transformers:
- polymer:
    entry_points:
    - web/index.html
environment:
  sdk: ">=1.2.0 <2.0.0"
